### PR TITLE
Thermal blanketing updates

### PR DESCRIPTION
**Pull request by jtvievering**
I made some small changes to the code that computes the absorption by thermal blanketing for the instrument response. Defaults are updated to provide the correct thickness of blanketing layers for FOXSI-2, and values for FOXSI-1 and FOXSI-3 are listed in the opening comments. Also, I simplified the setup so that just one array is used to contain the thicknesses of the layers instead of two. 

With these changes to correct the FOXSI-2 default values, there is a small change in the blanketing efficiency (~10% at 4 keV), so those who are working on FOXSI-2 analysis should take note of this change!

Note: Also, I had some Github usage snafus which is why there are a number of unrelated commits-- these all cancel each other out, so the only file that should be changed is the blanketing code.

### CODE REVIEW

**Comment by somusset** [comment]
I do not see any problem with this update.

**Comment by jtvievering** [comment]
I'll plan to merge this pull request by the end of the day tomorrow (Tuesday, Feb 19) if there are no additional comments.

**Comment by LinErinG** [comment]
@jtvievering I checked the values one more time and came up with the same ones you did for all three flights.  My only remaining note is that the keyword NONSTD is currently not doing anything -- the only way to get a blanketing-free optical path is to manually set all the material thicknesses to zero.  If you want NONSTD to take precedence over the material thicknesses, just move its definition down a few lines.

**Comment by jtvievering** [comment]
Thanks, Lindsay! I made the suggested change.

**Comment by LinErinG** [comment]
This pull request looks good to me.

**Pull request merged**
