### PR TITLE
Adding the foxsi_image_cut.pro routine

### PR DESCRIPTION
**Pull request by pymilo**
This routine computes a 2D intensity array cut on a circular area of
interest for a single detector, in detector coords. By default returns
a map, but can return the number of counts inside the circle or the
good_fraction by using the appropriate keywords.

### CODE REVIEW

**Comment by LinErinG** [comment]
@pymilo This is a great start.  As we discussed on Skype earlier today, the next steps are to:

1. Add an option to return the count flux instead of counts (in counts/sec/keV)
2. Return the statistical uncertainty (for the flux option)
3. Divide by the effective area (using the OFFAXIS keyword to appropriately take into account the vignetting effect) to get the result in incident photon flux instead of counts.

An additional thought is that for the flux we should also divide by the area of the circle, so that the returned value is counts (or photons) / second / keV / area on the Sun.  That way we can compare values from one area to another.

**Comment by LinErinG** [comment]
Good progress.  I added some inline comments.  Especially see the note about the uncertainty calculation.  Also, can we get the uncertainty as a return value or output keyword?

**Comment by somusset** [comment]
Hi Milo and Lindsay,
Should this pull request be closed or accepted? It is 2 year old. I am asking because one of the files implicated is area_cut.pro and we will soon have other updates made to this file, so I was wondering if we need to have Milo's updates accepted first.

**Comment by LinErinG** [comment]
@pymilo Please see Sophie's question.

**Comment by pymilo** [comment]
I think we are happy with the routine we have. We can accept this pull, so everybody can have this tool at hand. In the future, I would like to edit this routine to use not only a circular region but another area given by the user. That could be useful for instance for my quiet sun and ghost rays analysis.

For now, it is good enough, and to follow the tradition, Sophie you can try to test it works for you following the example given in lines 32 and 33 of the script before accepting it :)

**Comment by pymilo** [comment]
Great! Thanks Sophie!

**Pull request merged**
